name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version_part:
        description: 'Part of the version to bump (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # needed to create release and push commits
      
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    
    - name: Bump version
      run: |
        poetry version ${{ github.event.inputs.version_part }}
        NEW_VERSION=$(poetry version -s)
        echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
    
    - name: Commit and push changes
      run: |
        git add pyproject.toml
        git commit -m "Bump version to ${NEW_VERSION}"
        git push
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.NEW_VERSION }}
        release_name: Release v${{ env.NEW_VERSION }}
        draft: false
        prerelease: false