name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with Black
      run: |
        poetry run black --check .
    - name: Lint with isort
      run: |
        pip install isort==6.0.1
        isort --check .
    - name: Type check with mypy
      run: |
        poetry run mypy namecheap
    - name: Lint with Ruff
      run: |
        poetry run ruff check .