name: Publish Python Package

# This workflow is triggered by the release.yml workflow
# No need for manual triggers, as release.yml handles everything
on:
  push:
    tags:
      - 'v*.*.*'  # Run when tag matches v*, e.g., v1.0.0, v2.3.4

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/namecheap-python
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build poetry
    - name: Set version from tag (if triggered by tag)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        # Extract version from the tag
        TAG_NAME=${GITHUB_REF#refs/tags/}
        VERSION=${TAG_NAME#v}
        echo "Using version from tag: ${VERSION}"
        
        # Set version in pyproject.toml (single source of truth)
        poetry version ${VERSION}
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1